services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ".:/app"
    environment:
      RAILS_ENV: development
      DATABASE_URL: ${DB_DRIVER}://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_DATABASE}
      depends_on:
        db
    stdin_open: true
    tty: true

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}

    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:${DB_PORT}"

volumes:
  postgres_data:

